<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'contact/pdf/address-box'                   => __DIR__ . '//view/contact/pdf/address-box.twig',
    'contact/contact/change-password'           => __DIR__ . '//view/contact/contact/change-password.twig',
    'contact/contact/profile'                   => __DIR__ . '//view/contact/contact/profile.twig',
    'contact/contact/profile-edit'              => __DIR__ . '//view/contact/contact/profile-edit.twig',
    'contact/contact/signature'                 => __DIR__ . '//view/contact/contact/signature.twig',
    'contact/contact-manager/impersonate'       => __DIR__ . '//view/contact/contact-manager/impersonate.twig',
    'contact/contact-manager/edit'              => __DIR__ . '//view/contact/contact-manager/edit.twig',
    'contact/contact-manager/permit'            => __DIR__ . '//view/contact/contact-manager/permit.twig',
    'contact/contact-manager/list'              => __DIR__ . '//view/contact/contact-manager/list.twig',
    'contact/contact-manager/view'              => __DIR__ . '//view/contact/contact-manager/view.twig',
    'contact/contact-manager/new'               => __DIR__ . '//view/contact/contact-manager/new.twig',
    'contact/contact-manager/partial/general'   => __DIR__ . '//view/contact/contact-manager/partial/general.twig',
    'contact/contact-manager/partial/phone'     => __DIR__ . '//view/contact/contact-manager/partial/phone.twig',
    'contact/contact-manager/partial/selection' => __DIR__ . '//view/contact/contact-manager/partial/selection.twig',
    'contact/contact-manager/partial/project'   => __DIR__ . '//view/contact/contact-manager/partial/project.twig',
    'contact/contact-manager/partial/event'     => __DIR__ . '//view/contact/contact-manager/partial/event.twig',
    'contact/contact-manager/partial/address'   => __DIR__ . '//view/contact/contact-manager/partial/address.twig',
    'contact/partial/pagination-control'        => __DIR__ . '//view/contact/partial/pagination-control.twig',
    'contact/partial/entity/contact'            => __DIR__ . '//view/contact/partial/entity/contact.twig',
    'contact/partial/signature'                 => __DIR__ . '//view/contact/partial/signature.twig',
);
