<?php
_("txt-not-hide-for-others");
_("txt-hide-for-others");
_("txt-not-hide-photo");
_("txt-hide-photo");
_("txt-visibility-hidden");
_("txt-visibility-community");
_("txt-visibility-public");
_("txt-attention");
_("txt-first-name");
_("txt-middle-name");
_("txt-last-name");
_("txt-phone-number");
_("txt-zip-code");
_("txt-city");
_("txt-visibility");
_("txt-photo-file");
