<?php
_("txt-opt-in-title-placeholder');P
_('txt-opt-in-title-title');P
_('txt-opt-in-title-help-block');P
_('txt-opt-in-active-title');P
_('txt-opt-in-active-help-block');P
_('txt-opt-in-description-placeholder');P
_('txt-opt-in-description-title');P
_('txt-opt-in-description-help-block');P
_('txt-inactive');P
_('txt-active');P
_('txt-phone-number');P
_('txt-type');P
_('txt-address');P
_('txt-zip-code');P
_('txt-city');P
_('txt-country');P
_('txt-facebook');P
_('txt-public');P
_('txt-can-send-message');P
_('txt-can-send-message-explanation');P
_('txt-from-clause');P
_('txt-from-clause-explanation');P
_('txt-where-clause');P
_('txt-where-clause-explanation');P
_('txt-orderby-clause');P
_('txt-orderby-clause-explanation');P
_('txt-contact-key');P
_('txt-contact-key-explanation');P
_('txt-title');P
_('txt-title-explanation');P
_('txt-sub-title');P
_('txt-sub-title-explanation');P
_('txt-show-email-title');P
_('txt-show-email-explanation');P
_('txt-show-phone-title');P
_('txt-show-phone-explanation');P
_('txt-facebook-access-label');P
_('txt-facebook-access-help-block');P
_('txt-empty');P
_('txt-organisation');P
_('txt-position');P
_('txt-projects');P
_('txt-hide-email');P
_('txt-show-email-to-members');P
_('txt-show-email-to-all');P
_('txt-hide-phone');P
_('txt-show-phone-to-members');P
_('txt-show-mobile-phone-to-members');P
_('txt-show-phone-to-all');P
_('txt-cannot-send-message');P
_('txt-not-public');P
_('txt-contact-dnd-program-label');P
_('txt-program-dnd-program-help-block');P
_('txt-dnd-file');P
_('txt-selection');P
_('txt-tag');P
_('txt-selection-note-placeholder');P
_('txt-selection-note-label');P
_('txt-selection-note-help-block');P
_('txt-selection-owner-label');P
_('txt-selection-owner-help-block');P
_('txt-selection-core-label');P
_('txt-selection-core-help-block');P
_('txt-not-core');P
_('txt-core');P
_('txt-note');P
_('txt-source');P
_('txt-factor');P
_('txt-on-calendar');P
_('txt-hours');P
_('txt-end-date');P
_('txt-calendar-color');P
_('txt-contact');P
_('txt-office-member');P
_('txt-description');P
_('txt-start-date');P
_('txt-expertise');P
_('txt-visibility');P
_('txt-visibility-community');P
_('txt-visibility-hidden');P
_('txt-contact-first-name-placeholder');P
_('txt-contact-first-name-label');P
_('txt-contact-first-name-help-block');P
_('txt-contact-middle-name-placeholder');P
_('txt-contact-middle-name-label');P
_('txt-contact-middle-name-help-block');P
_('txt-contact-last-name-placeholder');P
_('txt-contact-last-name-label');P
_('txt-contact-last-name-help-block');P
_('txt-contact-email-address-placeholder');P
_('txt-contact-email-address-label');P
_('txt-contact-email-address-help-block');P
_('txt-contact-gender-label');P
_('txt-contact-gender-help-block');P
_('txt-contact-title-label');P
_('txt-contact-title-help-block');P
_('txt-contact-position-placeholder');P
_('txt-contact-position-label');P
_('txt-contact-position-help-block');P
_('txt-contact-department-placeholder');P
_('txt-contact-department-label');P
_('txt-contact-department-help-block');P
_('txt-contact-date-of-birth-label');P
_('txt-contact-date-of-birth-help-block');P
_('txt-contact-access-label');P
_('txt-contact-access-help-block");
