<?php
_('txt-no-organisation-found-complete-your-profile-to-participate-in-projects-with-link-%s');
_('txt-no-event-registrations-were-found-for-this-contact');
_('txt-selection-has-been-deleted-on-%s');
_('txt-remove-from-selection');
_('txt-update-opt-in');
_('txt-selection-is-sql');
_('txt-remove');
_('txt-reset');
_('txt-select-all');
_('txt-add');
_('txt-activate-contact');
_('txt-de-activate-contact');
_('txt-flush-permissions');
